### ISSUE TITLE
Cannot load databricks-cdk dockerfile from cdk code

### ISSUE THREAD

**Issue by DaanRademaker** [godatadriven/databricks-cdk#1013]
There seems to be an issue with creating the deploy lambda from the databricks-cdk code. For me this issue has appeared from I think the 1.0 release? I get the following error:

```
[100%] fail: docker build --build-arg version=v0.11.8 --build-arg randomHash= --tag cdkasset-843fff560e25ec2fb84c3a073380084c6619f6ce268f7b78a4d9dd7adc827858 --file Dockerfile . exited with error code 1: #2 [internal] load .dockerignore
#2 sha256:6a66d730e6a982f7732660169b9ffa2ccdaf4d3806b0e3bee5b0746de5fe62e0
#2 transferring context: 2B done
#2 DONE 0.0s
#1 [internal] load build definition from Dockerfile
#1 sha256:c4c27166159593b0e3be33682c967b34d4406e67c282f6e6c83dfe281ae86d06
#1 transferring dockerfile: 84B done
#1 DONE 0.0s
#3 [internal] load metadata for docker.io/godatadriven/databricks-cdk-lambda:v0.11.8
#3 sha256:80729af1dd5f6df163a36275e6b80108e9a5c7f671a23bf7ccfd50084ebab95a
#3 ERROR: failed to do request: Head "https://172.27.51.159:5000/v2/godatadriven/databricks-cdk-lambda/manifests/v0.11.8?ns=docker.io": http: server gave HTTP response to HTTPS client
------
 > [internal] load metadata for docker.io/godatadriven/databricks-cdk-lambda:v0.11.8:
------
godatadriven/databricks-cdk-lambda:v0.11.8: failed to do request: Head "https://172.27.51.159:5000/v2/godatadriven/databricks-cdk-lambda/manifests/v0.11.8?ns=docker.io": http: server gave HTTP response to HTTPS client
 ❌ Building assets failed: Error: Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
    at buildAllStackAssets (/builds/datascience/platform/datascience-resources/deploy/node_modules/aws-cdk/lib/build.ts:21:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/builds/datascience/platform/datascience-resources/deploy/node_modules/aws-cdk/lib/cdk-toolkit.ts:174:7)
    at initCommandLine (/builds/datascience/platform/datascience-resources/deploy/node_modules/aws-cdk/lib/cli.ts:349:12)
```
I am not sure what's going on. I am able to pull the image. But the request for the manifests to "https://172.27.51.159:5000/v2/godatadriven/databricks-cdk-lambda/manifests" is also not working locally.

**Comment by dan1elt0m** [comment]
Fixed in 0.11.9
